### ISSUE TITLE
Register package?

### ISSUE THREAD

**Issue by GregPlowman** [ChenNingCong/SimpleTypeChecker#3]
Will `SimpleTypeChecker` be registered in the General registry?

**Comment by ChenNingCong** [comment]
Hi, I am considering whether I should register this package. Currently, this package is quite experimental and needs a lot of tests (though it should be quite stable and usable if you only use simple features of Juila). The internal is also undergoing a lot of changing. I don't want really to waste a name in the general registry. Anyway, we can always install it with `add http://....`

Also, whether Julia programmers really need a (Fortan/C-style) static type checker is a question that still bothers me. SimpleTypeChecker didn't get many responses from the community, but I am sure that many packages, especially those written by non-experts, suffer from varying degrees of type instablity. SimpleTypeChecker also has some official competitors, like `JET.jl` and `Cthulhu.jl`, sponsored and maintained by core developers. 

That's why it's still not registered, and my current plan is to do more investigations to convince other people the need of a static type checker.

**Comment by GregPlowman** [comment]
OK, makes sense. 
Thanks for the reply. 
Closing.
